CO1: Type: PI,  Action: D/A,  Proportional Band: 6DegF,  DeadBand: 0.0, 
     Reset Rate = 3, Reset Band = 6DegF
CO2: Type: PI,  Action: D/A,  Proportional Band: 30degF,  DeadBand: 0.0,  
     Reset Rate = 3, Reset Band: 10degF
CO3: Type PI,  Action: D/A,  Proportional Band: 20degF,  DeadBand: 0.0, Reset Rate = 3
     Reset Band = 5degF
CO4: Type P  Action: R/A,  Proportional Band: 10%RH,  DeadBand: 0.0, Bias = 0
